# Квартиры в Москве в 1997 году
#### Установить зависимость цены на квартиру от многочисленных параметров.
1 - цена, тыс. долларов;
2 - число комнат;
3 - жилая площадь, кв.м;
4 - площадь подсобных помещений, кв.м;
5 - площадь кухни и туалета, кв.м;
6 - расстояние до центра, км;
7 - время, затрачиваемое на дорогу до ближайшей станции метро, мин.
#### Построить зависимость параметра 1 от параметров 3-7.
Рассматриваем множественную регрессию вида:
$$ Y = a_0 + a_1X_1 + ... + a_nX_n, $$
где Y - столбец цен на квартиру, X1-Xn - столбцы параметров 3-7.
Для решения необходимо найти столбец коэффициентов a1-an.

In [1]:
import pandas as pd
import numpy as np

Для решения задачи и подготовки данных используем numpy и pandas.

In [2]:
data = pd.read_excel('Flats.xls')

In [3]:
data.head()

LIVSQ  APPEN  KITSQ  DIST  METRDIST  WALK  BRICK  TEL  BAL  FLOOR  ROOM  \
0   20.0    6.0   10.0  0.85       5.0     1      0    1    0      1     1   
1   19.8   11.2    9.0  3.93       2.0     1      0    1    1      1     1   
2   19.0    5.9    9.6  3.93       5.0     1      0    1    1      0     1   
3   17.6   17.3    7.9  4.47       5.0     1      1    1    1      1     1   
4   19.0    7.6    6.0  4.47      10.0     1      1    1    0      1     1   

   PRICE  
0   65.0  
1   43.0  
2   34.0  
3   75.0  
4   35.0

In [4]:
df = data[['ROOM','LIVSQ','APPEN','KITSQ','DIST','METRDIST']].loc[data.ROOM == 3]

In [5]:
df.head()

ROOM  LIVSQ  APPEN  KITSQ    DIST  METRDIST
288     3   54.0   16.5    9.5   7.895       7.0
289     3   52.0   22.6    8.4   6.600       4.0
290     3   39.5   13.3    8.0  16.500      10.0
291     3   53.0   10.7    8.3   1.840      10.0
292     3   63.0   18.0    7.0   1.650      10.0

В df записываем столбцы таблицы по которым строим зависимость цена на квартиру. Используем 4-ёх комнатные квартиры. 

In [6]:
y = data['PRICE'].loc[data.ROOM == 3]
y = y.to_numpy()
y

array([ 75. , 110. ,  63. , 101. , 142. , 100. , 103. ,  40.5,  47. ,
        40.5,  65. ,  76. ,  93. ,  47. ,  53. ,  86. , 115. ,  82. ,
        53. ,  40. ,  57. ,  58. ,  48. ,  71. ,  55. ,  56.5, 133. ,
       185. ,  94. ,  61.5,  56. , 112. , 255. ,  88. ,  75. ,  41. ,
        51. ,  60. ,  74.5,  49. ,  58. ,  67. ,  62. ,  67. ,  53. ,
        53.8,  52. ,  69. , 112.5,  81. ,  53. ,  95. ,  86. ,  80. ,
        58. ,  65. ,  49.5,  66. ,  52. ,  95. ,  85. ,  89. ,  59.5,
        95.5,  80. ,  80. , 145. ,  74. ,  83. , 120. ,  89. , 135. ,
       125. ,  48. ,  69. ,  69. ,  90. , 165. , 207. ,  95.5, 111.5,
       122. , 105. ,  87. ,  87. , 240. , 145. ,  38. , 103. ,  58.5,
       106. ,  35. ,  58. ,  58. ,  69. ,  90.5,  68. ,  89. , 117. ,
        76. ,  78. , 112. ,  77. ,  92. ,  89. , 107. ,  75. ,  64. ,
        86. ,  62. , 110. ,  78. ,  67. , 108. ,  95. , 106. ,  62. ,
        64. ,  93. ,  92. ])

In [7]:
df.ROOM.replace(3,1, inplace=True) 
df.head()

ROOM  LIVSQ  APPEN  KITSQ    DIST  METRDIST
288     1   54.0   16.5    9.5   7.895       7.0
289     1   52.0   22.6    8.4   6.600       4.0
290     1   39.5   13.3    8.0  16.500      10.0
291     1   53.0   10.7    8.3   1.840      10.0
292     1   63.0   18.0    7.0   1.650      10.0

In [8]:
x = df.to_numpy()
x

array([[ 1.    , 54.    , 16.5   ,  9.5   ,  7.895 ,  7.    ],
       [ 1.    , 52.    , 22.6   ,  8.4   ,  6.6   ,  4.    ],
       [ 1.    , 39.5   , 13.3   ,  8.    , 16.5   , 10.    ],
       [ 1.    , 53.    , 10.7   ,  8.3   ,  1.84  , 10.    ],
       [ 1.    , 63.    , 18.    ,  7.    ,  1.65  , 10.    ],
       [ 1.    , 52.    , 15.    ,  8.    ,  1.805 ,  5.    ],
       [ 1.    , 49.    , 18.5   ,  8.5   ,  8.2   ,  5.    ],
       [ 1.    , 33.9   , 10.6   ,  6.    , 15.1   , 10.    ],
       [ 1.    , 35.7   , 12.6   ,  5.2   , 13.5   ,  4.    ],
       [ 1.    , 45.    ,  9.7   ,  6.8   , 14.15  ,  7.    ],
       [ 1.    , 44.    , 11.    , 11.    ,  4.735 , 10.    ],
       [ 1.    , 43.    , 17.3   ,  6.7   ,  3.5   ,  2.    ],
       [ 1.    , 47.    , 18.    ,  9.    ,  4.45  , 10.    ],
       [ 1.    , 42.    , 12.5   ,  6.3   , 15.2   , 10.    ],
       [ 1.    , 45.3   , 12.4   ,  6.6   , 15.3   ,  5.    ],
       [ 1.    , 53.    , 19.    ,  8.    ,  7.7   ,  3

Столбец ROOM заполняем 1, т.к. он будет соответствовать коэф. a0.
Преобразуем таблицу в массив x.

Для нахождения вектора коэфф.-ов используем преобразование
$$a = 1/(X^TX) = X^TY $$

In [9]:
def predict_of_price(x,y):
    """
    Функия предсказывает цену на квартиры. X - матрица пар.-ов(от которых у зависит), 
    Y -  массив действительных цен на кв.
    """
    t = (x.T).dot(x)
    t = np.linalg.inv(t)
    t1 = x.T.dot(y)
    global a
    a = t.dot(t1)
    guess_y = y*0
    for i in range(0,len(x)):
        for j in range(0,len(x[i])):
            guess_y[i] += a[j]*x[i][j]
    return guess_y

In [10]:
guess_y = predict_of_price(x,y)
a

array([-6.01612593e+01,  1.95335503e+00,  1.49056700e+00,  4.92103501e+00,
       -1.48265326e+00,  3.45591740e-03])

В функции predict_price при помощи методов T(транспонирование матрицы), dot(умножение матрицы) и linalg.inv(вычисление обратной матрицы) находим вектор коэф-ов в соотвествии с предложенным преобразованием. Далее записываем в guess_y предположительные цены на квартиры, высчитывая их по уравнению множественной регресии.

In [11]:
df['PRICE'] = y
df['GUESS_PRICE'] = guess_y
df.head()

ROOM  LIVSQ  APPEN  KITSQ    DIST  METRDIST  PRICE  GUESS_PRICE
288     1   54.0   16.5    9.5   7.895       7.0   75.0   104.982744
289     1   52.0   22.6    8.4   6.600       4.0  110.0   106.665023
290     1   39.5   13.3    8.0  16.500      10.0   63.0    51.759866
291     1   53.0   10.7    8.3   1.840      10.0  101.0    97.466692
292     1   63.0   18.0    7.0   1.650      10.0  142.0   121.765740

In [12]:
pogr = (abs(df.PRICE - df.GUESS_PRICE)).mean()
pogr

16.900338328998544

Добавим в нашу таблицу столбцы с реальными и предположительными ценами. Заметим, что данные отличаются. Вычислим среднюю погрешность. Она равна 23,3 тыс.долларов.

Теперь решим эту же задачу уже используя эластичность.
$$Y = a_0X_1^{a_1}...X_n^{a_n}$$
Прологарифмируем обе части этого выражения для применения известных нам преобразований.
$$lnY = lna_0 + a_1lnX_1 + ... + a_nlnX_n$$

In [13]:
def predict_ln_price(x,y):
    """
    Функия предсказывает цену на квартиры с помощью эластичности. X - матрица пар.-ов(от которых у зависит), 
    Y -  массив действительных цен на кв.
    """
    lny = np.log(y)
    lnx = np.log(x)
    for i in range(0,len(lnx)):
        lnx[i][0] += 1
    t = (lnx.T).dot(lnx)
    t = np.linalg.inv(t)
    t1 = lnx.T.dot(lny)
    global lna
    lna = t.dot(t1)
    guess_lny=y/y*np.exp(lna[0])
    for i in range(0,len(x)):
        for j in range(1,len(x[i])):
            guess_lny[i] *= np.power(x[i][j],lna[j])
    return guess_lny
guess_lny = predict_ln_price(x,y)

В начале созда1м переменные lny и lnx для хранения логарифмов массива y и матрицы x соответственно. Первый столбец матрицы x получится нулевым, для дальнейших вычислений приравняем его единице. Совершаем преобразование и находим вектор коэф.-ов lna. Теперь воспользуемся формулой эластичности, но перед этим в переменную guss_lny записываем единичный вектор и умножаем его на $e^{lna_0}$, т.е. $a_0$. Далее с помощью метода .power возваодим x в соответствующую степень a, в итоге получеам вектор предпологаемых цен.

In [14]:
df['GUESS_LN_PRICE'] = guess_lny
df.head()

ROOM  LIVSQ  APPEN  KITSQ    DIST  METRDIST  PRICE  GUESS_PRICE  \
288     1   54.0   16.5    9.5   7.895       7.0   75.0   104.982744   
289     1   52.0   22.6    8.4   6.600       4.0  110.0   106.665023   
290     1   39.5   13.3    8.0  16.500      10.0   63.0    51.759866   
291     1   53.0   10.7    8.3   1.840      10.0  101.0    97.466692   
292     1   63.0   18.0    7.0   1.650      10.0  142.0   121.765740   

     GUESS_LN_PRICE  
288       96.556697  
289       98.122281  
290       57.307184  
291       97.720458  
292      124.580737

In [15]:
lnpogr = (abs(df.PRICE - df.GUESS_LN_PRICE)).mean()
lnpogr

16.069380159564904

In [16]:
pogr-lnpogr

0.8309581694336394